[
  {"deps/nostrum/lib/nostrum/consumer.ex", "Function Nostrum.ConsumerGroup.join/1 does not exist."},
  {"lib/service/discord.ex", "Function Nostrum.Api.create_message/2 does not exist."},
  {"lib/service/discord.ex", "Function Nostrum.Api.get_channel_message/2 does not exist."},
  {"lib/service/discord.ex", "Function Nostrum.Cache.Me.get/0 does not exist."},
  {"lib/service/discord.ex", "Function Nostrum.Struct.User.full_name/1 does not exist."},
  {"lib/stampede/application.ex", "Function Mix.env/0 does not exist."},
  {"lib/stampede/interact.ex", "Function Mix.env/0 does not exist."},
  {"/build/source/lib/elixir/lib/gen_server.ex", "Callback info about the Nostrum.Consumer behaviour is not available."},
  {"lib/plugin.ex", "Function job_result/0 has no local return."},
  {"lib/plugin.ex", "Function plugin_job_result/0 has no local return."},
  {"lib/service/discord.ex", "Function logger_state/0 has no local return."},
  {"lib/service/dummy.ex", "@spec for send_msg has more types than are returned by the function."},
  {"lib/service/dummy.ex", "Function dummy_channel_id/0 has no local return."},
  {"lib/service/dummy.ex", "Function dummy_msg_id/0 has no local return."},
  {"lib/service/dummy.ex", "Function msg_content/0 has no local return."},
  {"lib/service/dummy.ex", "Function msg_reference/0 has no local return."},
  {"lib/service/dummy.ex", "Function msg_tuple/0 has no local return."},
  {"lib/service/dummy.ex", "Function msg_tuple_incoming/0 has no local return."},
  {"lib/service/dummy.ex", "Function channel/0 has no local return."},
  {"lib/service/dummy.ex", "Function channel_buffers/0 has no local return."},
  {"lib/service/dummy.ex", "Function dummy_servers/0 has no local return."},
  {"lib/site_config.ex", "Function schema/0 has no local return."},
  {"lib/stampede.ex", "Function log_level/0 has no local return."},
  {"lib/stampede.ex", "Function log_msg/0 has no local return."},
  {"lib/stampede.ex", "Function prefix/0 has no local return."},
  {"lib/stampede.ex", "Function module_function_args/0 has no local return."},
  {"lib/stampede.ex", "Function io_list/0 has no local return."},
  {"lib/stampede.ex", "Function traceback/0 has no local return."},
  {"lib/stampede.ex", "Function enabled_plugs/0 has no local return."},
  {"lib/stampede.ex", "Function channel_lock_action/0 has no local return."},
  {"lib/stampede.ex", "Function channel_lock_status/0 has no local return."},
  {"lib/stampede.ex", "Function throw_internal_error/0 has no local return."},
  {"lib/stampede.ex", "Function throw_internal_error/1 only terminates with explicit exception."},
  {"lib/stampede/interact.ex", "Function mod_state/0 has no local return."},
  {"deps/type_check/lib/type_check/spec.ex", "The pattern can never match the type {:ok, [], _}."}
]
